name: portfolio
description: Portfolio website
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: 3.13.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  vector_math: any

  # Localization
  flutter_localizations:
    sdk: flutter

  # Navigation and layout
  go_router: ^10.1.1
  multi_split_view: ^2.4.0
  assorted_layout_widgets: ^8.0.4

  # Local storage and database
  shared_preferences: ^2.1.1

  # Device, package and app utils
  dynamic_color: ^1.6.5
  material_color_utilities: ^0.5.0

  # Types annotations

  # Data types and utils
  rxdart: ^0.27.7
  intl: ^0.18.0
  collection: ^1.16.0

  # Animation, images, videos and other external widgets
  rive: ^0.11.14
  animations: ^2.0.7
  flutter_svg: ^2.0.7
  video_player: ^2.7.0
  video_player_platform_interface: any # ! Have to use it to reach [VideoPlayerWebOptions]

  # Replace with the original [https://pub.dev/packages/styled_text] when it supports sync parsing. Issue [https://github.com/andyduke/styled_text_package/issues/65]
  styled_text:
    git:
      url: https://github.com/Maatteogekko/styled_text_package.git
      ref: 57dd8b9
      path: styled_text

  # Open system UI views
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  build_verify: ^3.1.0
  intl_utils: ^2.8.4
  flutter_gen_runner: ^5.3.1
  go_router_builder: ^2.3.0

# https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl
flutter_intl:
  enabled: true
  class_name: Dictums
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated

flutter_gen:
  output: lib/flutter_gen
  line_length: 120

flutter:
  uses-material-design: true

  # * Don't forget to run the code generation command after adding a new asset here:
  assets:
    # Third-party logos
    - assets/images/third_party/firebase_logomark.svg
    - assets/images/third_party/google_material_design_logo.svg
    - assets/images/third_party/git_logomark.svg
    - assets/images/third_party/logo_dart.svg
    - assets/images/third_party/github_icon.svg
    - assets/images/third_party/google_play_logomark.svg
    - assets/images/third_party/app_store_logomark.svg
    - assets/images/third_party/github_actions_logomark.svg
    - assets/images/third_party/freska-service-workers-app-icon.svg
    - assets/images/third_party/freska-customer-app-icon.svg
    - assets/images/third_party/github_icon.svg
    - assets/images/third_party/freska-f-icon.svg

    - assets/images/illustrations/hard_skills/dart_aot_compile.svg
    - assets/images/illustrations/hard_skills/cicd.png
    - assets/images/illustrations/hard_skills/version_control.svg
    - assets/images/illustrations/hard_skills/material_design.png
    - assets/images/illustrations/hard_skills/design_system.png
    - assets/images/illustrations/hard_skills/i18n.svg
    - assets/images/illustrations/hard_skills/app_deployment.png

    - assets/images/illustrations/freska_app/preview.png
    - assets/images/illustrations/freska_app/preview2.png
    - assets/images/illustrations/freska_app/home_page_before.png
    - assets/images/illustrations/freska_app/home_page_after.png
    - assets/images/illustrations/freska_app/booking_details_before.png
    - assets/images/illustrations/freska_app/booking_details_after.png
    - assets/images/illustrations/freska_app/account_details_before.png
    - assets/images/illustrations/freska_app/account_details_after.png
    - assets/images/illustrations/freska_app/rescheduling_before.png
    - assets/images/illustrations/freska_app/rescheduling_after.png

    - assets/images/illustrations/freska_pro_app/preview.png
    - assets/images/illustrations/freska_pro_app/booking_details.png
    - assets/images/illustrations/freska_pro_app/schedule.png

    # Animations
    - assets/animations/under_construction.riv
    - assets/animations/utopic_narwhal.riv

    # Videos
    - assets/videos/flutter_developing.mp4
    - assets/videos/responsive_layout.mp4
    - assets/videos/firebase_hero_loop.webm

    - assets/fonts/victor_mono/OFL.txt
    - assets/fonts/inter/OFL.txt

  fonts:
    - family: "VictorMono"
      fonts:
        - asset: assets/fonts/victor_mono/VictorMono-VariableFont_wght.ttf
    - family: "Inter"
      fonts:
        - asset: assets/fonts/inter/Inter-VariableFont_slnt,wght.ttf
