name: freska-fi/superhero-native/workflow

on:
  workflow_dispatch:
  push:
    branches: ['main', 'master']

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.0
    - name: Setup Flutter
      uses: subosito/flutter-action@v2.10.0
      with:
        flutter-version: '3.10.6'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:'

    - name: Build the web release
      run: flutter build web --release --no-tree-shake-icons

    - name: Publish to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
        domain: github.io
        target_branch: gh-pages
        build_dir: build/web
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

