name: utopicnarwhal/utopicnarwhal.github.io/workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.0
    - name: Setup Flutter
      uses: subosito/flutter-action@v2.10.0
      with:
        flutter-version: '3.13.0'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:'

    - name: Build the web release
      run: flutter build web --release --base-href "/" --web-renderer canvaskit

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      with:
        folder: build/web
